/*******************************************************************************
 * Copyright (C) 2005-2016 Alfresco Software Limited.
 *
 * This file is part of the Alfresco Activiti Mobile SDK.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 ******************************************************************************/

#import "NSString+ASDKFontGlyphicons.h"

#if ! __has_feature(objc_arc)
#warning This file must be compiled with ARC. Use -fobjc-arc flag (or convert project to ARC).
#endif

@implementation NSString (ASDKFontGlyphicons)

#pragma mark -
#pragma mark Public interface

+ (NSString *)iconStringForIconType:(ASDKGlyphIconType)iconType {
    if (ASDKGlyphIconTypeUndefined != iconType) {
        return [NSString fontGlyphiconsUnicodeStrings][iconType];
    }
    return nil;
}

+ (ASDKGlyphIconType)iconTypeForIcontDescription:(NSString *)iconDescription {
    // First check if icon description is registered
    NSNumber *iconDescriptionCorrespondentValue = [self iconDescriptions][iconDescription];
    if (iconDescriptionCorrespondentValue) {
        return (ASDKGlyphIconType)[iconDescriptionCorrespondentValue integerValue];
    }
    
    return ASDKGlyphIconTypeUndefined;
}

- (NSString *)normalizedIconDescriptionName {
    return [self stringByReplacingOccurrencesOfString:@"glyphicon-"
                                           withString:@"glyphicons-"];
}

#pragma mark -
#pragma mark Private interface

+ (NSArray *)fontGlyphiconsUnicodeStrings {
    static NSArray *fontGlyphiconsUnicodeStrings;
    
    static dispatch_once_t unicodeStringsOnceToken;
    dispatch_once(&unicodeStringsOnceToken, ^{
        fontGlyphiconsUnicodeStrings = @[@"\uE001",@"\uE002",@"\uE003",@"\uE004",@"\uE005",@"\uE006",@"\uE007",@"\uE008",@"\uE009",@"\uE010",@"\u2709",@"\uE012",@"\uE013",@"\uE014",@"\uE015",@"\uE016",@"\uE017",@"\uE018",@"\uE019",@"\uE020",@"\uE021",@"\uE022",@"\uE023",@"\uE024",@"\uE025",@"\uE026",@"\uE027",@"\uE028",@"\uE029",@"\uE030",@"\u270F",@"\uE032",@"\uE033",@"\uE034",@"\uE035",@"\uE036",@"\uE037",@"\uE038",@"\uE039",@"\uE040",@"\uE041",@"\uE042",@"\uE043",@"\uE044",@"\uE045",@"\uE046",@"\uE047",@"\uE048",@"\uE049",@"\uE050",@"\uE051",@"\uE052",@"\uE053",@"\uE054",@"\uE055",@"\uE056",@"\uE057",@"\uE058",@"\uE059",@"\uE060",@"\uE061",@"\uE062",@"\uE063",@"\uE064",@"\uE065",@"\uE066",@"\uE067",@"\uE068",@"\uE069",@"\uE070",@"\uE071",@"\uE072",@"\uE073",@"\uE074",@"\uE075",@"\uE076",@"\uE077",@"\uE078",@"\uE079",@"\uE080",@"\uE081",@"\uE082",@"\uE083",@"\uE084",@"\uE085",@"\uE086",@"\uE087",@"\uE088",@"\uE089",@"\uE090",@"\uE091",@"\uE092",@"\uE093",@"\uE094",@"\uE095",@"\uE096",@"\uE097",@"\uE098",@"\uE099",@"\uE100",@"\uE101",@"\uE102",@"\uE103",@"\uE104",@"\uE105",@"\uE106",@"\uE107",@"\uE108",@"\uE109",@"\uE110",@"\uE111",@"\uE112",@"\uE113",@"\uE114",@"\uE115",@"\uE116",@"\uE117",@"\uE118",@"\uE119",@"\uE120",@"\uE121",@"\uE122",@"\uE123",@"\uE124",@"\uE125",@"\uE126",@"\uE127",@"\uE128",@"\uE129",@"\uE130",@"\uE131",@"\uE132",@"\uE133",@"\uE134",@"\uE135",@"\uE136",@"\uE137",@"\uE138",@"\uE139",@"\uE140",@"\uE141",@"\uE142",@"\uE143",@"\uE144",@"\uE145",@"\uE146",@"\uE147",@"\uE148",@"\uE149",@"\uE150",@"\uE151",@"\uE152",@"\uE153",@"\uE154",@"\uE155",@"\uE156",@"\uE157",@"\uE158",@"\uE159",@"\uE160",@"\uE161",@"\uE162",@"\uE163",@"\uE164",@"\uE165",@"\uE166",@"\uE167",@"\uE168",@"\uE169",@"\uE170",@"\uE171",@"\uE172",@"\uE173",@"\uE174",@"\uE175",@"\uE176",@"\uE177",@"\uE178",@"\uE179",@"\uE180",@"\uE181",@"\uE182",@"\uE183",@"\uE184",@"\uE185",@"\uE186",@"\uE187",@"\uE188",@"\uE189",@"\uE190",@"\uE191",@"\uE192",@"\uE193",@"\uE194",@"\uE195",@"\uE196",@"\uE197",@"\uE198",@"\uE199",@"\uE200",@"\uE201",@"\uE202",@"\uE203",@"\uE204",@"\uE205",@"\uE206",@"\uE207",@"\uE208",@"\uE209",@"\uE210",@"\uE211",@"\uE212",@"\uE213",@"\uE214",@"\uE215",@"\uE216",@"\uE217",@"\uE218",@"\uE219",@"\uE220",@"\uE221",@"\uE222",@"\uE223",@"\uE224",@"\uE225",@"\uE226",@"€",@"\uE228",@"\uE229",@"\uE230",@"\uE231",@"\uE232",@"\u2601",@"\uE234",@"\uE235",@"\uE236",@"\uE237",@"\uE238",@"\uE239",@"\uE240",@"\uE241",@"\uE242",@"\uE243",@"\uE244",@"\uE245",@"\uE246",@"\uE247",@"\uE248",@"*",@"\uE250",@"\uE251",@"\uE252",@"\uE253",@"\uE254",@"\uE255",@"\uE256",@"\uE257",@"\uE258",@"\uE259",@"\uE260",@"\uE261",@"\uE262",@"\uE263",@"\uE264",@"\uE265",@"\uE266",@"\uE267",@"\uE268",@"\uE269",@"\uE270",@"\uE271",@"\uE272",@"\uE273",@"\uE274",@"\uE275",@"\uE276",@"\uE277",@"\uE278",@"\uE279",@"\uE280",@"\uE281",@"\uE282",@"\uE283",@"\uE284",@"\uE285",@"\uE286",@"\uE287",@"\uE288",@"\uE289",@"\uE290",@"\uE291",@"\uE292",@"\uE293",@"\uE294",@"\uE295",@"\uE296",@"\uE297",@"\uE298",@"\uE299",@"\uE300",@"\uE301",@"\uE302",@"\uE303",@"\uE304",@"\uE305",@"\uE306",@"\uE307",@"\uE308",@"\uE309",@"\uE310",@"\uE311",@"\uE312",@"\uE313",@"\uE314",@"\uE315",@"\uE316",@"\uE317",@"\uE318",@"\uE319",@"\uE320",@"\uE321",@"\uE322",@"\uE323",@"\uE324",@"\uE325",@"\uE326",@"\uE327",@"\uE328",@"\uE329",@"\uE330",@"\uE331",@"\uE332",@"\uE333",@"\uE334",@"\uE335",@"\uE336",@"\uE337",@"\uE338",@"\uE339",@"\uE340",@"\uE341",@"\uE342",@"\uE343",@"\uE344",@"\uE345",@"\uE346",@"\uE347",@"\uE348",@"\uE349",@"\uE350",@"\uE351",@"\uE352",@"\uE353",@"\uE354",@"\uE355",@"\uE356",@"\uE357",@"\uE358",@"\uE359",@"\uE360",@"\uE361",@"\uE362",@"\uE363",@"\uE364",@"\uE365",@"\uE366",@"\uE367",@"\uE368",@"\uE369",@"\uE370",@"\uE371",@"\uE372",@"\uE373",@"\uE374",@"\uE375",@"\uE376",@"\uE377",@"\uE378",@"\uE379",@"\uE380",@"\uE381",@"\uE382",@"\uE383",@"\uE384",@"\uE385",@"\uE386",@"\uE387",@"\uE388",@"\uE389",@"\uE390",@"\uE391",@"\uE392",@"\uE393",@"\uE394",@"\uE395",@"\uE396",@"\uE397",@"\uE398",@"\uE399",@"\uE400",@"\uE401",@"\uE402",@"\uE403",@"\uE404",@"\uE405",@"\uE406",@"\uE407",@"\uE408",@"\uE409",@"\uE410",@"\uE411",@"\uE412",@"\uE413",@"\uE414",@"\uE415",@"\uE416",@"\uE417",@"\uE418",@"\uE419",@"\uE420",@"\uE421",@"\uE422",@"\uE423",@"\uE424",@"\uE425",@"\uE426",@"\uE427",@"\uE428",@"\uE429",@"\uE430",@"\uE431",@"\uE432",@"+",@"\uE434",@"\uE435",@"\uE436",@"\uE437",@"\uE438",@"\uE439",@"\uE440",@"\uE441",@"\uE442",@"\uE443",@"\uE444",@"\uE445",@"\uE446",@"\uE447",@"\uE448",@"\uE449",@"\uE450",@"\uE451",@"\uE452",@"\uE453",@"\uE454",@"\uE455",@"\uE456",@"\uE457",@"\uE458",@"\uE459",@"\uE460",@"\uE461",@"\uE462",@"\uE463",@"\uE464",@"\uE465",@"\uE466",@"\uE467",@"\uE468",@"\uE469",@"\uE470",@"\uE471",@"\uE472",@"\uE473",@"\uE474",@"\uE475",@"\uE476",@"\uE477",@"\uE478",@"\uE479",@"\uE480",@"\uE481",@"\uE482",@"\uE483",@"\uE484",@"\uE485",@"\uE486",@"\uE487",@"\uE488",@"\uE489",@"\uE490",@"\uE491",@"\uE492",@"\uE493",@"\uE494",@"\uE495",@"\uE496",@"\uE497",@"\uE498",@"\uE499",@"\uE500",@"\uE501",@"\uE502",@"\uE503",@"\uE504",@"\uE505",@"\uE506",@"\uE507",@"\uE508",@"\uE509",@"\uE510",@"\uE511",@"\uE512",@"\uE513",@"\uE514",@"\uE515",@"\uE516",@"\uE517",@"\uE518",@"\uE519",@"\uE520",@"\uE521",@"\uE522",@"\uE523",@"\uE524",@"\uE525",@"\uE526",@"\uE527",@"\uE528",@"\uE529",@"\uE530",@"\uE531",@"\uE532",@"\uE533",@"\uE534",@"\uE535",@"\uE536",@"\uE537",@"\uE538",@"\uE539",@"\uE540",@"\uE541",@"\uE542",@"\uE543",@"\uE544",@"\uE545",@"\uE546",@"\uE547",@"\uE548",@"\uE549",@"\uE550",@"\uE551",@"\uE552",@"\uE553",@"\uE554",@"\uE555",@"\uE556",@"\uE557",@"\uE558",@"\uE559",@"\uE560",@"\uE561",@"\uE562",@"\uE563",@"\uE564",@"\uE565",@"\uE566",@"\uE567",@"\uE568",@"\uE569",@"\uE570",@"\uE571",@"\uE572",@"\uE573",@"\uE574",@"\uE575",@"\uE576",@"\uE577",@"\uE578",@"\uE579",@"\uE580",@"\uE581",@"\uE582",@"\uE583",@"\uE584",@"\uE585",@"\uE586",@"\uE587",@"\uE588",@"\uE589",@"\uE590",@"\uE591",@"\uE592",@"\uE593",@"\uE594",@"\uE595",@"\uE596",@"\uE597",@"\uE598",@"\uE599",@"\uE600",@"\uE601",@"\uE602",@"\uE603",@"\uE604",@"\uE605",@"\uE606",@"\uE607",@"\uE608",@"\uE609",@"\uE610"];
    });
    
    return fontGlyphiconsUnicodeStrings;
}

+ (NSDictionary *)iconDescriptions {
    static NSDictionary *iconsDescriptionsDict;
    
    static dispatch_once_t iconDescriptionsOnceToken;
    dispatch_once(&iconDescriptionsOnceToken, ^{
        iconsDescriptionsDict = @{
                                  @"glyphicons-glass"           : @(ASDKGlyphIconTypeGlass),
                                  @"glyphicons-leaf"			: @(ASDKGlyphIconTypeLeaf),
                                  @"glyphicons-dog"				: @(ASDKGlyphIconTypeDog),
                                  @"glyphicons-user"			: @(ASDKGlyphIconTypeUser),
                                  @"glyphicons-girl"			: @(ASDKGlyphIconTypeGirl),
                                  @"glyphicons-car"				: @(ASDKGlyphIconTypeCar),
                                  @"glyphicons-user-add"		: @(ASDKGlyphIconTypeUserAdd),
                                  @"glyphicons-user-remove"		: @(ASDKGlyphIconTypeUserRemove),
                                  @"glyphicons-film"			: @(ASDKGlyphIconTypeFilm),
                                  @"glyphicons-magic"			: @(ASDKGlyphIconTypeMagic),
                                  @"glyphicons-envelope"        : @(ASDKGlyphIconTypeEnvelope),
                                  @"glyphicons-camera"			: @(ASDKGlyphIconTypeCamera),
                                  @"glyphicons-heart"			: @(ASDKGlyphIconTypeHeart),
                                  @"glyphicons-beach-umbrella"	: @(ASDKGlyphIconTypeBeachUmbrella),
                                  @"glyphicons-train"			: @(ASDKGlyphIconTypeTrain),
                                  @"glyphicons-print"			: @(ASDKGlyphIconTypePrint),
                                  @"glyphicons-bin"				: @(ASDKGlyphIconTypeBin),
                                  @"glyphicons-music"			: @(ASDKGlyphIconTypeMusic),
                                  @"glyphicons-note"			: @(ASDKGlyphIconTypeNote),
                                  @"glyphicons-heart-empty"		: @(ASDKGlyphIconTypeHeartEmpty),
                                  @"glyphicons-home"			: @(ASDKGlyphIconTypeHome),
                                  @"glyphicons-snowflake"		: @(ASDKGlyphIconTypeSnowflake),
                                  @"glyphicons-fire"			: @(ASDKGlyphIconTypeFire),
                                  @"glyphicons-magnet"			: @(ASDKGlyphIconTypeMagnet),
                                  @"glyphicons-parents"			: @(ASDKGlyphIconTypeParents),
                                  @"glyphicons-binoculars"		: @(ASDKGlyphIconTypeBinoculars),
                                  @"glyphicons-road"			: @(ASDKGlyphIconTypeRoad),
                                  @"glyphicons-search"			: @(ASDKGlyphIconTypeSearch),
                                  @"glyphicons-cars"			: @(ASDKGlyphIconTypeCars),
                                  @"glyphicons-notes-2"			: @(ASDKGlyphIconTypeNotes2),
                                  @"glyphicons-pencil"			: @(ASDKGlyphIconTypePencil),
                                  @"glyphicons-bus"				: @(ASDKGlyphIconTypeBus),
                                  @"glyphicons-wifi-alt"		: @(ASDKGlyphIconTypeWifiAlt),
                                  @"glyphicons-luggage"			: @(ASDKGlyphIconTypeLuggage),
                                  @"glyphicons-old-man"			: @(ASDKGlyphIconTypeOldMan),
                                  @"glyphicons-woman"			: @(ASDKGlyphIconTypeWoman),
                                  @"glyphicons-file"			: @(ASDKGlyphIconTypeFile),
                                  @"glyphicons-coins"			: @(ASDKGlyphIconTypeCoins),
                                  @"glyphicons-airplane"		: @(ASDKGlyphIconTypeAirplane),
                                  @"glyphicons-notes"			: @(ASDKGlyphIconTypeNotes),
                                  @"glyphicons-stats"			: @(ASDKGlyphIconTypeStats),
                                  @"glyphicons-charts"			: @(ASDKGlyphIconTypeCharts),
                                  @"glyphicons-pie-chart"		: @(ASDKGlyphIconTypePieChart),
                                  @"glyphicons-group"			: @(ASDKGlyphIconTypeGroup),
                                  @"glyphicons-keys"			: @(ASDKGlyphIconTypeKeys),
                                  @"glyphicons-calendar"		: @(ASDKGlyphIconTypeCalendar),
                                  @"glyphicons-router"			: @(ASDKGlyphIconTypeRouter),
                                  @"glyphicons-camera-small"	: @(ASDKGlyphIconTypeCameraSmall),
                                  @"glyphicons-star-empty"		: @(ASDKGlyphIconTypeStarEmpty),
                                  @"glyphicons-star"			: @(ASDKGlyphIconTypeStar),
                                  @"glyphicons-link"			: @(ASDKGlyphIconTypeLink),
                                  @"glyphicons-eye-open"		: @(ASDKGlyphIconTypeEyeOpen),
                                  @"glyphicons-eye-close"		: @(ASDKGlyphIconTypeEyeClose),
                                  @"glyphicons-alarm"			: @(ASDKGlyphIconTypeAlarm),
                                  @"glyphicons-clock"			: @(ASDKGlyphIconTypeClock),
                                  @"glyphicons-stopwatch"		: @(ASDKGlyphIconTypeStopwatch),
                                  @"glyphicons-projector"		: @(ASDKGlyphIconTypeProjector),
                                  @"glyphicons-history"			: @(ASDKGlyphIconTypeHistory),
                                  @"glyphicons-truck"			: @(ASDKGlyphIconTypeTruck),
                                  @"glyphicons-cargo"			: @(ASDKGlyphIconTypeCargo),
                                  @"glyphicons-compass"			: @(ASDKGlyphIconTypeCompass),
                                  @"glyphicons-keynote"			: @(ASDKGlyphIconTypeKeynote),
                                  @"glyphicons-paperclip"		: @(ASDKGlyphIconTypePaperclip),
                                  @"glyphicons-power"			: @(ASDKGlyphIconTypePower),
                                  @"glyphicons-lightbulb"		: @(ASDKGlyphIconTypeLightbulb),
                                  @"glyphicons-tag"				: @(ASDKGlyphIconTypeTag),
                                  @"glyphicons-tags"			: @(ASDKGlyphIconTypeTags),
                                  @"glyphicons-cleaning"		: @(ASDKGlyphIconTypeCleaning),
                                  @"glyphicons-ruler"			: @(ASDKGlyphIconTypeRuler),
                                  @"glyphicons-gift"			: @(ASDKGlyphIconTypeGift),
                                  @"glyphicons-umbrella"		: @(ASDKGlyphIconTypeUmbrella),
                                  @"glyphicons-book"			: @(ASDKGlyphIconTypeBook),
                                  @"glyphicons-bookmark"		: @(ASDKGlyphIconTypeBookmark),
                                  @"glyphicons-wifi"			: @(ASDKGlyphIconTypeWifi),
                                  @"glyphicons-cup"				: @(ASDKGlyphIconTypeCup),
                                  @"glyphicons-stroller"		: @(ASDKGlyphIconTypeStroller),
                                  @"glyphicons-headphones"		: @(ASDKGlyphIconTypeHeadphones),
                                  @"glyphicons-headset"			: @(ASDKGlyphIconTypeHeadset),
                                  @"glyphicons-warning-sign"	: @(ASDKGlyphIconTypeWarningSign),
                                  @"glyphicons-signal"			: @(ASDKGlyphIconTypeSignal),
                                  @"glyphicons-retweet"			: @(ASDKGlyphIconTypeRetweet),
                                  @"glyphicons-refresh"			: @(ASDKGlyphIconTypeRefresh),
                                  @"glyphicons-roundabout"		: @(ASDKGlyphIconTypeRoundabout),
                                  @"glyphicons-random"			: @(ASDKGlyphIconTypeRandom),
                                  @"glyphicons-heat"			: @(ASDKGlyphIconTypeHeat),
                                  @"glyphicons-repeat"			: @(ASDKGlyphIconTypeRepeat),
                                  @"glyphicons-display"			: @(ASDKGlyphIconTypeDisplay),
                                  @"glyphicons-log-book"		: @(ASDKGlyphIconTypeLogBook),
                                  @"glyphicons-address-book"	: @(ASDKGlyphIconTypeAddressBook),
                                  @"glyphicons-building"		: @(ASDKGlyphIconTypeBuilding),
                                  @"glyphicons-eyedropper"		: @(ASDKGlyphIconTypeEyedropper),
                                  @"glyphicons-adjust"			: @(ASDKGlyphIconTypeAdjust),
                                  @"glyphicons-tint"			: @(ASDKGlyphIconTypeTint),
                                  @"glyphicons-crop"				: @(ASDKGlyphIconTypeCrop),
                                  @"glyphicons-vector-path-square"	: @(ASDKGlyphIconTypeVectorPathSquare),
                                  @"glyphicons-vector-path-circle"	: @(ASDKGlyphIconTypeVectorPathCircle),
                                  @"glyphicons-vector-path-polygon"	: @(ASDKGlyphIconTypeVectorPathPolygon),
                                  @"glyphicons-vector-path-line"	: @(ASDKGlyphIconTypeVectorPathLine),
                                  @"glyphicons-vector-path-curve"	: @(ASDKGlyphIconTypeVectorPathCurve),
                                  @"glyphicons-vector-path-all"		: @(ASDKGlyphIconTypeVectorPathAll),
                                  @"glyphicons-font"				: @(ASDKGlyphIconTypeFont),
                                  @"glyphicons-italic"			: @(ASDKGlyphIconTypeItalic),
                                  @"glyphicons-bold"			: @(ASDKGlyphIconTypeBold),
                                  @"glyphicons-text-underline"	: @(ASDKGlyphIconTypeTextUnderline),
                                  @"glyphicons-text-strike"		: @(ASDKGlyphIconTypeTextStrike),
                                  @"glyphicons-text-height"		: @(ASDKGlyphIconTypeTextHeight),
                                  @"glyphicons-text-width"		: @(ASDKGlyphIconTypeTextWidth),
                                  @"glyphicons-text-resize"		: @(ASDKGlyphIconTypeTextResize),
                                  @"glyphicons-left-indent"		: @(ASDKGlyphIconTypeLeftIndent),
                                  @"glyphicons-right-indent"	: @(ASDKGlyphIconTypeRightIndent),
                                  @"glyphicons-align-left"		: @(ASDKGlyphIconTypeAlignLeft),
                                  @"glyphicons-align-center"	: @(ASDKGlyphIconTypeAlignCenter),
                                  @"glyphicons-align-right"		: @(ASDKGlyphIconTypeAlignRight),
                                  @"glyphicons-justify"			: @(ASDKGlyphIconTypeJustify),
                                  @"glyphicons-list"			: @(ASDKGlyphIconTypeList),
                                  @"glyphicons-text-smaller"	: @(ASDKGlyphIconTypeTextSmaller),
                                  @"glyphicons-text-bigger"		: @(ASDKGlyphIconTypeTextBigger),
                                  @"glyphicons-embed"			: @(ASDKGlyphIconTypeEmbed),
                                  @"glyphicons-embed-close"		: @(ASDKGlyphIconTypeEmbedClose),
                                  @"glyphicons-table"			: @(ASDKGlyphIconTypeTable),
                                  @"glyphicons-message-full"	: @(ASDKGlyphIconTypeMessageFull),
                                  @"glyphicons-message-empty"	: @(ASDKGlyphIconTypeMessageEmpty),
                                  @"glyphicons-message-in"		: @(ASDKGlyphIconTypeMessageIn),
                                  @"glyphicons-message-out"		: @(ASDKGlyphIconTypeMessageOut),
                                  @"glyphicons-message-plus"	: @(ASDKGlyphIconTypeMessagePlus),
                                  @"glyphicons-message-minus"	: @(ASDKGlyphIconTypeMessageMinus),
                                  @"glyphicons-message-ban"		: @(ASDKGlyphIconTypeMessageBan),
                                  @"glyphicons-message-flag"	: @(ASDKGlyphIconTypeMessageFlag),
                                  @"glyphicons-message-lock"	: @(ASDKGlyphIconTypeMessageLock),
                                  @"glyphicons-message-new"		: @(ASDKGlyphIconTypeMessageNew),
                                  @"glyphicons-inbox"			: @(ASDKGlyphIconTypeInbox),
                                  @"glyphicons-inbox-plus"		: @(ASDKGlyphIconTypeInboxPlus),
                                  @"glyphicons-inbox-minus"		: @(ASDKGlyphIconTypeInboxMinus),
                                  @"glyphicons-inbox-lock"		: @(ASDKGlyphIconTypeInboxLock),
                                  @"glyphicons-inbox-in"		: @(ASDKGlyphIconTypeInboxIn),
                                  @"glyphicons-inbox-out"		: @(ASDKGlyphIconTypeInboxOut),
                                  @"glyphicons-cogwheel"		: @(ASDKGlyphIconTypeCogwheel),
                                  @"glyphicons-cogwheels"		: @(ASDKGlyphIconTypeCogwheels),
                                  @"glyphicons-picture"			: @(ASDKGlyphIconTypePicture),
                                  @"glyphicons-adjust-alt"		: @(ASDKGlyphIconTypeAdjustAlt),
                                  @"glyphicons-database-lock"	: @(ASDKGlyphIconTypeDatabaseLock),
                                  @"glyphicons-database-plus"	: @(ASDKGlyphIconTypeDatabasePlus),
                                  @"glyphicons-database-minus"	: @(ASDKGlyphIconTypeDatabaseMinus),
                                  @"glyphicons-database-ban"	: @(ASDKGlyphIconTypeDatabaseBan),
                                  @"glyphicons-folder-open"		: @(ASDKGlyphIconTypeFolderOpen),
                                  @"glyphicons-folder-plus"     : @(ASDKGlyphIconTypeFolderPlus),
                                  @"glyphicons-folder-minus"	: @(ASDKGlyphIconTypeFolderMinus),
                                  @"glyphicons-folder-lock"		: @(ASDKGlyphIconTypeFolderLock),
                                  @"glyphicons-folder-flag"		: @(ASDKGlyphIconTypeFolderFlag),
                                  @"glyphicons-folder-new"		: @(ASDKGlyphIconTypeFolderNew),
                                  @"glyphicons-edit"			: @(ASDKGlyphIconTypeEdit),
                                  @"glyphicons-new-window"		: @(ASDKGlyphIconTypeNewWindow),
                                  @"glyphicons-check"			: @(ASDKGlyphIconTypeCheck),
                                  @"glyphicons-unchecked"		: @(ASDKGlyphIconTypeUnchecked),
                                  @"glyphicons-more-windows"	: @(ASDKGlyphIconTypeMoreWindows),
                                  @"glyphicons-show-big-thumbnails"         : @(ASDKGlyphIconTypeShowBigThumbnails),
                                  @"glyphicons-show-thumbnails"             : @(ASDKGlyphIconTypeShowThumbnails),
                                  @"glyphicons-show-thumbnails-with-lines"	: @(ASDKGlyphIconTypeShowThumbnailsWithLines),
                                  @"glyphicons-show-lines"		: @(ASDKGlyphIconTypeShowLines),
                                  @"glyphicons-playlist"		: @(ASDKGlyphIconTypePlaylist),
                                  @"glyphicons-imac"			: @(ASDKGlyphIconTypeImac),
                                  @"glyphicons-macbook"			: @(ASDKGlyphIconTypeMacbook),
                                  @"glyphicons-ipad"			: @(ASDKGlyphIconTypeIpad),
                                  @"glyphicons-iphone"			: @(ASDKGlyphIconTypeIphone),
                                  @"glyphicons-iphone-transfer"	: @(ASDKGlyphIconTypeIphoneTransfer),
                                  @"glyphicons-iphone-exchange"	: @(ASDKGlyphIconTypeIphoneExchange),
                                  @"glyphicons-ipod"			: @(ASDKGlyphIconTypeIpod),
                                  @"glyphicons-ipod-shuffle"	: @(ASDKGlyphIconTypeIpodShuffle),
                                  @"glyphicons-ear-plugs"		: @(ASDKGlyphIconTypeEarPlugs),
                                  @"glyphicons-record"			: @(ASDKGlyphIconTypeRecord),
                                  @"glyphicons-step-backward"	: @(ASDKGlyphIconTypeStepBackward),
                                  @"glyphicons-fast-backward"	: @(ASDKGlyphIconTypeFastBackward),
                                  @"glyphicons-rewind"			: @(ASDKGlyphIconTypeRewind),
                                  @"glyphicons-play"			: @(ASDKGlyphIconTypePlay),
                                  @"glyphicons-pause"			: @(ASDKGlyphIconTypePause),
                                  @"glyphicons-stop"			: @(ASDKGlyphIconTypeStop),
                                  @"glyphicons-forward"			: @(ASDKGlyphIconTypeForward),
                                  @"glyphicons-fast-forward"	: @(ASDKGlyphIconTypeFastForward),
                                  @"glyphicons-step-forward"	: @(ASDKGlyphIconTypeStepForward),
                                  @"glyphicons-eject"			: @(ASDKGlyphIconTypeEject),
                                  @"glyphicons-facetime-video"	: @(ASDKGlyphIconTypeFacetimeVideo),
                                  @"glyphicons-download-alt"	: @(ASDKGlyphIconTypeDownloadAlt),
                                  @"glyphicons-mute"			: @(ASDKGlyphIconTypeMute),
                                  @"glyphicons-volume-down"		: @(ASDKGlyphIconTypeVolumeDown),
                                  @"glyphicons-volume-up"		: @(ASDKGlyphIconTypeVolumeUp),
                                  @"glyphicons-screenshot"		: @(ASDKGlyphIconTypeScreenshot),
                                  @"glyphicons-move"			: @(ASDKGlyphIconTypeMove),
                                  @"glyphicons-more"			: @(ASDKGlyphIconTypeMore),
                                  @"glyphicons-brightness-reduce"		: @(ASDKGlyphIconTypeBrightnessReduce),
                                  @"glyphicons-brightness-increase"		: @(ASDKGlyphIconTypeBrightnessIncrease),
                                  @"glyphicons-circle-plus"				: @(ASDKGlyphIconTypeCirclePlus),
                                  @"glyphicons-circle-minus"			: @(ASDKGlyphIconTypeCircleMinus),
                                  @"glyphicons-circle-remove"			: @(ASDKGlyphIconTypeCircleRemove),
                                  @"glyphicons-circle-ok"				: @(ASDKGlyphIconTypeCircleOk),
                                  @"glyphicons-circle-question-mark"	: @(ASDKGlyphIconTypeCircleQuestionMark),
                                  @"glyphicons-circle-info"				: @(ASDKGlyphIconTypeCircleInfo),
                                  @"glyphicons-circle-exclamation-mark"	: @(ASDKGlyphIconTypeCircleExclamationMark),
                                  @"glyphicons-remove"			: @(ASDKGlyphIconTypeRemove),
                                  @"glyphicons-ok"				: @(ASDKGlyphIconTypeOk),
                                  @"glyphicons-ban"				: @(ASDKGlyphIconTypeBan),
                                  @"glyphicons-download"		: @(ASDKGlyphIconTypeDownload),
                                  @"glyphicons-upload"			: @(ASDKGlyphIconTypeUpload),
                                  @"glyphicons-shopping-cart"	: @(ASDKGlyphIconTypeShoppingCart),
                                  @"glyphicons-lock"			: @(ASDKGlyphIconTypeLock),
                                  @"glyphicons-unlock"			: @(ASDKGlyphIconTypeUnlock),
                                  @"glyphicons-electricity"     : @(ASDKGlyphIconTypeElectricity),
                                  @"glyphicons-ok-2"			: @(ASDKGlyphIconTypeOk2),
                                  @"glyphicons-remove-2"		: @(ASDKGlyphIconTypeRemove2),
                                  @"glyphicons-cart-out"		: @(ASDKGlyphIconTypeCartOut),
                                  @"glyphicons-cart-in"			: @(ASDKGlyphIconTypeCartIn),
                                  @"glyphicons-left-arrow"		: @(ASDKGlyphIconTypeLeftArrow),
                                  @"glyphicons-right-arrow"		: @(ASDKGlyphIconTypeRightArrow),
                                  @"glyphicons-down-arrow"		: @(ASDKGlyphIconTypeDownArrow),
                                  @"glyphicons-up-arrow"		: @(ASDKGlyphIconTypeUpArrow),
                                  @"glyphicons-resize-small"	: @(ASDKGlyphIconTypeResizeSmall),
                                  @"glyphicons-resize-full"		: @(ASDKGlyphIconTypeResizeFull),
                                  @"glyphicons-circle-arrow-left"   : @(ASDKGlyphIconTypeCircleArrowLeft),
                                  @"glyphicons-circle-arrow-right"	: @(ASDKGlyphIconTypeCircleArrowRight),
                                  @"glyphicons-circle-arrow-top"	: @(ASDKGlyphIconTypeCircleArrowTop),
                                  @"glyphicons-circle-arrow-down"	: @(ASDKGlyphIconTypeCircleArrowDown),
                                  @"glyphicons-play-button"			: @(ASDKGlyphIconTypePlayButton),
                                  @"glyphicons-unshare"			: @(ASDKGlyphIconTypeUnshare),
                                  @"glyphicons-share"			: @(ASDKGlyphIconTypeShare),
                                  @"glyphicons-chevron-right"	: @(ASDKGlyphIconTypeChevronRight),
                                  @"glyphicons-chevron-left"	: @(ASDKGlyphIconTypeChevronLeft),
                                  @"glyphicons-bluetooth"		: @(ASDKGlyphIconTypeBluetooth),
                                  @"glyphicons-euro"			: @(ASDKGlyphIconTypeEuro),
                                  @"glyphicons-usd"				: @(ASDKGlyphIconTypeUsd),
                                  @"glyphicons-gbp"				: @(ASDKGlyphIconTypeGbp),
                                  @"glyphicons-retweet-2"		: @(ASDKGlyphIconTypeRetweet2),
                                  @"glyphicons-moon"			: @(ASDKGlyphIconTypeMoon),
                                  @"glyphicons-sun"				: @(ASDKGlyphIconTypeSun),
                                  @"glyphicons-cloud"			: @(ASDKGlyphIconTypeCloud),
                                  @"glyphicons-direction"       : @(ASDKGlyphIconTypeDirection),
                                  @"glyphicons-brush"			: @(ASDKGlyphIconTypeBrush),
                                  @"glyphicons-pen"				: @(ASDKGlyphIconTypePen),
                                  @"glyphicons-zoom-in"			: @(ASDKGlyphIconTypeZoomIn),
                                  @"glyphicons-zoom-out"		: @(ASDKGlyphIconTypeZoomOut),
                                  @"glyphicons-pin"				: @(ASDKGlyphIconTypePin),
                                  @"glyphicons-albums"			: @(ASDKGlyphIconTypeAlbums),
                                  @"glyphicons-rotation-lock"	: @(ASDKGlyphIconTypeRotationLock),
                                  @"glyphicons-flash"			: @(ASDKGlyphIconTypeFlash),
                                  @"glyphicons-google-maps"		: @(ASDKGlyphIconTypeGoogleMaps),
                                  @"glyphicons-anchor"			: @(ASDKGlyphIconTypeAnchor),
                                  @"glyphicons-conversation"	: @(ASDKGlyphIconTypeConversation),
                                  @"glyphicons-chat"			: @(ASDKGlyphIconTypeChat),
                                  @"glyphicons-male"			: @(ASDKGlyphIconTypeMale),
                                  @"glyphicons-female"			: @(ASDKGlyphIconTypeFemale),
                                  @"glyphicons-asterisk"		: @(ASDKGlyphIconTypeAsterisk),
                                  @"glyphicons-divide"			: @(ASDKGlyphIconTypeDivide),
                                  @"glyphicons-snorkel-diving"	: @(ASDKGlyphIconTypeSnorkelDiving),
                                  @"glyphicons-scuba-diving"	: @(ASDKGlyphIconTypeScubaDiving),
                                  @"glyphicons-oxygen-bottle"	: @(ASDKGlyphIconTypeOxygenBottle),
                                  @"glyphicons-fins"			: @(ASDKGlyphIconTypeFins),
                                  @"glyphicons-fishes"			: @(ASDKGlyphIconTypeFishes),
                                  @"glyphicons-boat"			: @(ASDKGlyphIconTypeBoat),
                                  @"glyphicons-delete"          : @(ASDKGlyphIconTypeDelete),
                                  @"glyphicons-sheriffs-star"	: @(ASDKGlyphIconTypeSheriffsStar),
                                  @"glyphicons-qrcode"			: @(ASDKGlyphIconTypeQrcode),
                                  @"glyphicons-barcode"			: @(ASDKGlyphIconTypeBarcode),
                                  @"glyphicons-pool"			: @(ASDKGlyphIconTypePool),
                                  @"glyphicons-buoy"			: @(ASDKGlyphIconTypeBuoy),
                                  @"glyphicons-spade"			: @(ASDKGlyphIconTypeSpade),
                                  @"glyphicons-bank"			: @(ASDKGlyphIconTypeBank),
                                  @"glyphicons-vcard"			: @(ASDKGlyphIconTypeVcard),
                                  @"glyphicons-electrical-plug"	: @(ASDKGlyphIconTypeElectricalPlug),
                                  @"glyphicons-flag"			: @(ASDKGlyphIconTypeFlag),
                                  @"glyphicons-credit-card"		: @(ASDKGlyphIconTypeCreditCard),
                                  @"glyphicons-keyboard-wireless": @(ASDKGlyphIconTypeKeyboardWireless),
                                  @"glyphicons-keyboard-wired"	: @(ASDKGlyphIconTypeKeyboardWired),
                                  @"glyphicons-shield"			: @(ASDKGlyphIconTypeShield),
                                  @"glyphicons-ring"			: @(ASDKGlyphIconTypeRing),
                                  @"glyphicons-cake"			: @(ASDKGlyphIconTypeCake),
                                  @"glyphicons-drink"			: @(ASDKGlyphIconTypeDrink),
                                  @"glyphicons-beer"			: @(ASDKGlyphIconTypeBeer),
                                  @"glyphicons-fast-food"		: @(ASDKGlyphIconTypeFastFood),
                                  @"glyphicons-cutlery"			: @(ASDKGlyphIconTypeCutlery),
                                  @"glyphicons-pizza"			: @(ASDKGlyphIconTypePizza),
                                  @"glyphicons-birthday-cake"	: @(ASDKGlyphIconTypeBirthdayCake),
                                  @"glyphicons-tablet"			: @(ASDKGlyphIconTypeTablet),
                                  @"glyphicons-settings"		: @(ASDKGlyphIconTypeSettings),
                                  @"glyphicons-bullets"			: @(ASDKGlyphIconTypeBullets),
                                  @"glyphicons-cardio"			: @(ASDKGlyphIconTypeCardio),
                                  @"glyphicons-t-shirt"			: @(ASDKGlyphIconTypeTShirt),
                                  @"glyphicons-pants"			: @(ASDKGlyphIconTypePants),
                                  @"glyphicons-sweater"			: @(ASDKGlyphIconTypeSweater),
                                  @"glyphicons-fabric"			: @(ASDKGlyphIconTypeFabric),
                                  @"glyphicons-leather"			: @(ASDKGlyphIconTypeLeather),
                                  @"glyphicons-scissors"		: @(ASDKGlyphIconTypeScissors),
                                  @"glyphicons-bomb"			: @(ASDKGlyphIconTypeBomb),
                                  @"glyphicons-skull"			: @(ASDKGlyphIconTypeSkull),
                                  @"glyphicons-celebration"		: @(ASDKGlyphIconTypeCelebration),
                                  @"glyphicons-tea-kettle"		: @(ASDKGlyphIconTypeTeaKettle),
                                  @"glyphicons-french-press"	: @(ASDKGlyphIconTypeFrenchPress),
                                  @"glyphicons-coffee-cup"		: @(ASDKGlyphIconTypeCoffeeCup),
                                  @"glyphicons-pot"				: @(ASDKGlyphIconTypePot),
                                  @"glyphicons-grater"			: @(ASDKGlyphIconTypeGrater),
                                  @"glyphicons-kettle"			: @(ASDKGlyphIconTypeKettle),
                                  @"glyphicons-hospital"		: @(ASDKGlyphIconTypeHospital),
                                  @"glyphicons-hospital-h"		: @(ASDKGlyphIconTypeHospitalH),
                                  @"glyphicons-microphone"		: @(ASDKGlyphIconTypeMicrophone),
                                  @"glyphicons-webcam"          : @(ASDKGlyphIconTypeWebcam),
                                  @"glyphicons-temple-christianity-church"	: @(ASDKGlyphIconTypeTempleChristianityChurch),
                                  @"glyphicons-temple-islam"    : @(ASDKGlyphIconTypeTempleIslam),
                                  @"glyphicons-temple-hindu"    : @(ASDKGlyphIconTypeTempleHindu),
                                  @"glyphicons-temple-buddhist"	: @(ASDKGlyphIconTypeTempleBuddhist),
                                  @"glyphicons-bicycle"			: @(ASDKGlyphIconTypeBicycle),
                                  @"glyphicons-life-preserver"  : @(ASDKGlyphIconTypeLifePreserver),
                                  @"glyphicons-share-alt"       : @(ASDKGlyphIconTypeShareAlt),
                                  @"glyphicons-comments"		: @(ASDKGlyphIconTypeComments),
                                  @"glyphicons-flower"			: @(ASDKGlyphIconTypeFlower),
                                  @"glyphicons-baseball"		: @(ASDKGlyphIconTypeBaseball),
                                  @"glyphicons-rugby"			: @(ASDKGlyphIconTypeRugby),
                                  @"glyphicons-ax"				: @(ASDKGlyphIconTypeAx),
                                  @"glyphicons-table-tennis"	: @(ASDKGlyphIconTypeTableTennis),
                                  @"glyphicons-bowling"			: @(ASDKGlyphIconTypeBowling),
                                  @"glyphicons-tree-conifer"	: @(ASDKGlyphIconTypeTreeConifer),
                                  @"glyphicons-tree-deciduous"	: @(ASDKGlyphIconTypeTreeDeciduous),
                                  @"glyphicons-more-items"		: @(ASDKGlyphIconTypeMoreItems),
                                  @"glyphicons-sort"			: @(ASDKGlyphIconTypeSort),
                                  @"glyphicons-filter"			: @(ASDKGlyphIconTypeFilter),
                                  @"glyphicons-gamepad"			: @(ASDKGlyphIconTypeGamepad),
                                  @"glyphicons-playing-dices"	: @(ASDKGlyphIconTypePlayingDices),
                                  @"glyphicons-calculator"		: @(ASDKGlyphIconTypeCalculator),
                                  @"glyphicons-tie"				: @(ASDKGlyphIconTypeTie),
                                  @"glyphicons-wallet"			: @(ASDKGlyphIconTypeWallet),
                                  @"glyphicons-piano"			: @(ASDKGlyphIconTypePiano),
                                  @"glyphicons-sampler"			: @(ASDKGlyphIconTypeSampler),
                                  @"glyphicons-podium"			: @(ASDKGlyphIconTypePodium),
                                  @"glyphicons-soccer-ball"		: @(ASDKGlyphIconTypeSoccerBall),
                                  @"glyphicons-blog"			: @(ASDKGlyphIconTypeBlog),
                                  @"glyphicons-dashboard"       : @(ASDKGlyphIconTypeDashboard),
                                  @"glyphicons-certificate"		: @(ASDKGlyphIconTypeCertificate),
                                  @"glyphicons-bell"			: @(ASDKGlyphIconTypeBell),
                                  @"glyphicons-candle"			: @(ASDKGlyphIconTypeCandle),
                                  @"glyphicons-pushpin"			: @(ASDKGlyphIconTypePushpin),
                                  @"glyphicons-iphone-shake"    : @(ASDKGlyphIconTypeIphoneShake),
                                  @"glyphicons-pin-flag"		: @(ASDKGlyphIconTypePinFlag),
                                  @"glyphicons-turtle"			: @(ASDKGlyphIconTypeTurtle),
                                  @"glyphicons-rabbit"			: @(ASDKGlyphIconTypeRabbit),
                                  @"glyphicons-globe"			: @(ASDKGlyphIconTypeGlobe),
                                  @"glyphicons-briefcase"		: @(ASDKGlyphIconTypeBriefcase),
                                  @"glyphicons-hdd"				: @(ASDKGlyphIconTypeHdd),
                                  @"glyphicons-thumbs-up"		: @(ASDKGlyphIconTypeThumbsUp),
                                  @"glyphicons-thumbs-down"		: @(ASDKGlyphIconTypeThumbsDown),
                                  @"glyphicons-hand-right"		: @(ASDKGlyphIconTypeHandRight),
                                  @"glyphicons-hand-left"		: @(ASDKGlyphIconTypeHandLeft),
                                  @"glyphicons-hand-up"			: @(ASDKGlyphIconTypeHandUp),
                                  @"glyphicons-hand-down"		: @(ASDKGlyphIconTypeHandDown),
                                  @"glyphicons-fullscreen"		: @(ASDKGlyphIconTypeFullscreen),
                                  @"glyphicons-shopping-bag"	: @(ASDKGlyphIconTypeShoppingBag),
                                  @"glyphicons-book-open"		: @(ASDKGlyphIconTypeBookOpen),
                                  @"glyphicons-nameplate"		: @(ASDKGlyphIconTypeNameplate),
                                  @"glyphicons-nameplate-alt"	: @(ASDKGlyphIconTypeNameplateAlt),
                                  @"glyphicons-vases"			: @(ASDKGlyphIconTypeVases),
                                  @"glyphicons-bullhorn"		: @(ASDKGlyphIconTypeBullhorn),
                                  @"glyphicons-dumbbell"		: @(ASDKGlyphIconTypeDumbbell),
                                  @"glyphicons-suitcase"		: @(ASDKGlyphIconTypeSuitcase),
                                  @"glyphicons-file-import"		: @(ASDKGlyphIconTypeFileImport),
                                  @"glyphicons-file-export"		: @(ASDKGlyphIconTypeFileExport),
                                  @"glyphicons-bug"				: @(ASDKGlyphIconTypeBug),
                                  @"glyphicons-crown"			: @(ASDKGlyphIconTypeCrown),
                                  @"glyphicons-smoking"			: @(ASDKGlyphIconTypeSmoking),
                                  @"glyphicons-cloud-download"  : @(ASDKGlyphIconTypeCloudDownload),
                                  @"glyphicons-cloud-upload"	: @(ASDKGlyphIconTypeCloudUpload),
                                  @"glyphicons-restart"			: @(ASDKGlyphIconTypeRestart),
                                  @"glyphicons-security-camera" : @(ASDKGlyphIconTypeSecurityCamera),
                                  @"glyphicons-expand"			: @(ASDKGlyphIconTypeExpand),
                                  @"glyphicons-collapse"		: @(ASDKGlyphIconTypeCollapse),
                                  @"glyphicons-collapse-top"	: @(ASDKGlyphIconTypeCollapseTop),
                                  @"glyphicons-globe-af"		: @(ASDKGlyphIconTypeGlobeAf),
                                  @"glyphicons-global"			: @(ASDKGlyphIconTypeGlobal),
                                  @"glyphicons-spray"			: @(ASDKGlyphIconTypeSpray),
                                  @"glyphicons-nails"			: @(ASDKGlyphIconTypeNails),
                                  @"glyphicons-claw-hammer"		: @(ASDKGlyphIconTypeClawHammer),
                                  @"glyphicons-classic-hammer"	: @(ASDKGlyphIconTypeClassicHammer),
                                  @"glyphicons-hand-saw"		: @(ASDKGlyphIconTypeHandSaw),
                                  @"glyphicons-riflescope"		: @(ASDKGlyphIconTypeRiflescope),
                                  @"glyphicons-electrical-socket-eu" : @(ASDKGlyphIconTypeElectricalSocketEu),
                                  @"glyphicons-electrical-socket-us" : @(ASDKGlyphIconTypeElectricalSocketUs),
                                  @"glyphicons-message-forward"	: @(ASDKGlyphIconTypeMessageForward),
                                  @"glyphicons-coat-hanger"		: @(ASDKGlyphIconTypeCoatHanger),
                                  @"glyphicons-dress"			: @(ASDKGlyphIconTypeDress),
                                  @"glyphicons-bathrobe"		: @(ASDKGlyphIconTypeBathrobe),
                                  @"glyphicons-shirt"			: @(ASDKGlyphIconTypeShirt),
                                  @"glyphicons-underwear"		: @(ASDKGlyphIconTypeUnderwear),
                                  @"glyphicons-log-in"			: @(ASDKGlyphIconTypeLogIn),
                                  @"glyphicons-log-out"			: @(ASDKGlyphIconTypeLogOut),
                                  @"glyphicons-exit"			: @(ASDKGlyphIconTypeExit),
                                  @"glyphicons-new-window-alt"	: @(ASDKGlyphIconTypeNewWindowAlt),
                                  @"glyphicons-video-sd"		: @(ASDKGlyphIconTypeVideoSd),
                                  @"glyphicons-video-hd"		: @(ASDKGlyphIconTypeVideoHd),
                                  @"glyphicons-subtitles"		: @(ASDKGlyphIconTypeSubtitles),
                                  @"glyphicons-sound-stereo"	: @(ASDKGlyphIconTypeSoundStereo),
                                  @"glyphicons-sound-dolby"		: @(ASDKGlyphIconTypeSoundDolby),
                                  @"glyphicons-sound-5-1"		: @(ASDKGlyphIconTypeSound51),
                                  @"glyphicons-sound-6-1"		: @(ASDKGlyphIconTypeSound61),
                                  @"glyphicons-sound-7-1"		: @(ASDKGlyphIconTypeSound71),
                                  @"glyphicons-copyright-mark"	: @(ASDKGlyphIconTypeCopyrightMark),
                                  @"glyphicons-registration-mark"        : @(ASDKGlyphIconTypeRegistrationMark),
                                  @"glyphicons-radar"                    : @(ASDKGlyphIconTypeRadar),
                                  @"glyphicons-skateboard"               : @(ASDKGlyphIconTypeSkateboard),
                                  @"glyphicons-golf-course"              : @(ASDKGlyphIconTypeGolfCourse),
                                  @"glyphicons-sorting"                  : @(ASDKGlyphIconTypeSorting),
                                  @"glyphicons-sort-by-alphabet"         : @(ASDKGlyphIconTypeSortByAlphabet),
                                  @"glyphicons-sort-by-alphabet-alt"     : @(ASDKGlyphIconTypeSortByAlphabetAlt),
                                  @"glyphicons-sort-by-order"            : @(ASDKGlyphIconTypeSortByOrder),
                                  @"glyphicons-sort-by-order-alt"        : @(ASDKGlyphIconTypeSortByOrderAlt),
                                  @"glyphicons-sort-by-attributes"       : @(ASDKGlyphIconTypeSortByAttributes),
                                  @"glyphicons-sort-by-attributes-alt"   : @(ASDKGlyphIconTypeSortByAttributesAlt),
                                  @"glyphicons-compressed"				 : @(ASDKGlyphIconTypeCompressed),
                                  @"glyphicons-package"			: @(ASDKGlyphIconTypePackage),
                                  @"glyphicons-cloud-plus"		: @(ASDKGlyphIconTypeCloudPlus),
                                  @"glyphicons-cloud-minus"		: @(ASDKGlyphIconTypeCloudMinus),
                                  @"glyphicons-disk-save"		: @(ASDKGlyphIconTypeDiskSave),
                                  @"glyphicons-disk-open"		: @(ASDKGlyphIconTypeDiskOpen),
                                  @"glyphicons-disk-saved"		: @(ASDKGlyphIconTypeDiskSaved),
                                  @"glyphicons-disk-remove"		: @(ASDKGlyphIconTypeDiskRemove),
                                  @"glyphicons-disk-import"		: @(ASDKGlyphIconTypeDiskImport),
                                  @"glyphicons-disk-export"		: @(ASDKGlyphIconTypeDiskExport),
                                  @"glyphicons-tower"			: @(ASDKGlyphIconTypeTower),
                                  @"glyphicons-send"			: @(ASDKGlyphIconTypeSend),
                                  @"glyphicons-git-branch"		: @(ASDKGlyphIconTypeGitBranch),
                                  @"glyphicons-git-create"		: @(ASDKGlyphIconTypeGitCreate),
                                  @"glyphicons-git-private"		: @(ASDKGlyphIconTypeGitPrivate),
                                  @"glyphicons-git-delete"		: @(ASDKGlyphIconTypeGitDelete),
                                  @"glyphicons-git-merge"		: @(ASDKGlyphIconTypeGitMerge),
                                  @"glyphicons-git-pull-request": @(ASDKGlyphIconTypeGitPullRequest),
                                  @"glyphicons-git-compare"		: @(ASDKGlyphIconTypeGitCompare),
                                  @"glyphicons-git-commit"		: @(ASDKGlyphIconTypeGitCommit),
                                  @"glyphicons-construction-cone": @(ASDKGlyphIconTypeConstructionCone),
                                  @"glyphicons-shoe-steps"		: @(ASDKGlyphIconTypeShoeSteps),
                                  @"glyphicons-plus"			: @(ASDKGlyphIconTypePlus),
                                  @"glyphicons-minus"           : @(ASDKGlyphIconTypeMinus),
                                  @"glyphicons-redo"            : @(ASDKGlyphIconTypeRedo),
                                  @"glyphicons-undo"			: @(ASDKGlyphIconTypeUndo),
                                  @"glyphicons-golf"			: @(ASDKGlyphIconTypeGolf),
                                  @"glyphicons-hockey"			: @(ASDKGlyphIconTypeHockey),
                                  @"glyphicons-pipe"			: @(ASDKGlyphIconTypePipe),
                                  @"glyphicons-wrench"			: @(ASDKGlyphIconTypeWrench),
                                  @"glyphicons-folder-closed"	: @(ASDKGlyphIconTypeFolderClosed),
                                  @"glyphicons-phone-alt"		: @(ASDKGlyphIconTypePhoneAlt),
                                  @"glyphicons-earphone"		: @(ASDKGlyphIconTypeEarphone),
                                  @"glyphicons-floppy-disk"		: @(ASDKGlyphIconTypeFloppyDisk),
                                  @"glyphicons-floppy-saved"	: @(ASDKGlyphIconTypeFloppySaved),
                                  @"glyphicons-floppy-remove"	: @(ASDKGlyphIconTypeFloppyRemove),
                                  @"glyphicons-floppy-save"		: @(ASDKGlyphIconTypeFloppySave),
                                  @"glyphicons-floppy-open"		: @(ASDKGlyphIconTypeFloppyOpen),
                                  @"glyphicons-translate"		: @(ASDKGlyphIconTypeTranslate),
                                  @"glyphicons-fax"				: @(ASDKGlyphIconTypeFax),
                                  @"glyphicons-factory"			: @(ASDKGlyphIconTypeFactory),
                                  @"glyphicons-shop-window"		: @(ASDKGlyphIconTypeShopWindow),
                                  @"glyphicons-shop"			: @(ASDKGlyphIconTypeShop),
                                  @"glyphicons-kiosk"			: @(ASDKGlyphIconTypeKiosk),
                                  @"glyphicons-kiosk-wheels"	: @(ASDKGlyphIconTypeKioskWheels),
                                  @"glyphicons-kiosk-light"		: @(ASDKGlyphIconTypeKioskLight),
                                  @"glyphicons-kiosk-food"		: @(ASDKGlyphIconTypeKioskFood),
                                  @"glyphicons-transfer"        : @(ASDKGlyphIconTypeTransfer),
                                  @"glyphicons-money"			: @(ASDKGlyphIconTypeMoney),
                                  @"glyphicons-header"			: @(ASDKGlyphIconTypeHeader),
                                  @"glyphicons-blacksmith"		: @(ASDKGlyphIconTypeBlacksmith),
                                  @"glyphicons-saw-blade"		: @(ASDKGlyphIconTypeSawBlade),
                                  @"glyphicons-basketball"		: @(ASDKGlyphIconTypeBasketball),
                                  @"glyphicons-server"			: @(ASDKGlyphIconTypeServer),
                                  @"glyphicons-server-plus"		: @(ASDKGlyphIconTypeServerPlus),
                                  @"glyphicons-server-minus"	: @(ASDKGlyphIconTypeServerMinus),
                                  @"glyphicons-server-ban"		: @(ASDKGlyphIconTypeServerBan),
                                  @"glyphicons-server-flag"		: @(ASDKGlyphIconTypeServerFlag),
                                  @"glyphicons-server-lock"		: @(ASDKGlyphIconTypeServerLock),
                                  @"glyphicons-server-new"		: @(ASDKGlyphIconTypeServerNew),
                                  @"glyphicons-charging-station": @(ASDKGlyphIconTypeChargingStation),
                                  @"glyphicons-gas-station"		: @(ASDKGlyphIconTypeGasStation),
                                  @"glyphicons-target"			: @(ASDKGlyphIconTypeTarget),
                                  @"glyphicons-bed-alt"			: @(ASDKGlyphIconTypeBedAlt),
                                  @"glyphicons-mosquito-net"	: @(ASDKGlyphIconTypeMosquitoNet),
                                  @"glyphicons-dining-set"		: @(ASDKGlyphIconTypeDiningSet),
                                  @"glyphicons-plate-of-food"	: @(ASDKGlyphIconTypePlateOfFood),
                                  @"glyphicons-hygiene-kit"		: @(ASDKGlyphIconTypeHygieneKit),
                                  @"glyphicons-blackboard"		: @(ASDKGlyphIconTypeBlackboard),
                                  @"glyphicons-marriage"        : @(ASDKGlyphIconTypeMarriage),
                                  @"glyphicons-bucket"			: @(ASDKGlyphIconTypeBucket),
                                  @"glyphicons-none-color-swatch": @(ASDKGlyphIconTypeNoneColorSwatch),
                                  @"glyphicons-bring-forward"	: @(ASDKGlyphIconTypeBringForward),
                                  @"glyphicons-bring-to-front"	: @(ASDKGlyphIconTypeBringToFront),
                                  @"glyphicons-send-backward"	: @(ASDKGlyphIconTypeSendBackward),
                                  @"glyphicons-send-to-back"		: @(ASDKGlyphIconTypeSendToBack),
                                  @"glyphicons-fit-frame-to-image"	: @(ASDKGlyphIconTypeFitFrameToImage),
                                  @"glyphicons-fit-image-to-frame"	: @(ASDKGlyphIconTypeFitImageToFrame),
                                  @"glyphicons-multiple-displays"	: @(ASDKGlyphIconTypeMultipleDisplays),
                                  @"glyphicons-handshake"		: @(ASDKGlyphIconTypeHandshake),
                                  @"glyphicons-child"			: @(ASDKGlyphIconTypeChild),
                                  @"glyphicons-baby-formula"	: @(ASDKGlyphIconTypeBabyFormula),
                                  @"glyphicons-medicine"		: @(ASDKGlyphIconTypeMedicine),
                                  @"glyphicons-atv-vehicle"		: @(ASDKGlyphIconTypeAtvVehicle),
                                  @"glyphicons-motorcycle"		: @(ASDKGlyphIconTypeMotorcycle),
                                  @"glyphicons-bed"				: @(ASDKGlyphIconTypeBed),
                                  @"glyphicons-tent"			: @(ASDKGlyphIconTypeTent),
                                  @"glyphicons-glasses"			: @(ASDKGlyphIconTypeGlasses),
                                  @"glyphicons-sunglasses"		: @(ASDKGlyphIconTypeSunglasses),
                                  @"glyphicons-family"          : @(ASDKGlyphIconTypeFamily),
                                  @"glyphicons-education"		: @(ASDKGlyphIconTypeEducation),
                                  @"glyphicons-shoes"			: @(ASDKGlyphIconTypeShoes),
                                  @"glyphicons-map"				: @(ASDKGlyphIconTypeMap),
                                  @"glyphicons-cd"				: @(ASDKGlyphIconTypeCd),
                                  @"glyphicons-alert"			: @(ASDKGlyphIconTypeAlert),
                                  @"glyphicons-piggy-bank"		: @(ASDKGlyphIconTypePiggyBank),
                                  @"glyphicons-star-half"		: @(ASDKGlyphIconTypeStarHalf),
                                  @"glyphicons-cluster"			: @(ASDKGlyphIconTypeCluster),
                                  @"glyphicons-flowchart"		: @(ASDKGlyphIconTypeFlowchart),
                                  @"glyphicons-commodities"		: @(ASDKGlyphIconTypeCommodities),
                                  @"glyphicons-duplicate"		: @(ASDKGlyphIconTypeDuplicate),
                                  @"glyphicons-copy"			: @(ASDKGlyphIconTypeCopy),
                                  @"glyphicons-paste"			: @(ASDKGlyphIconTypePaste),
                                  @"glyphicons-bath-bathtub"	: @(ASDKGlyphIconTypeBathBathtub),
                                  @"glyphicons-bath-shower"		: @(ASDKGlyphIconTypeBathShower),
                                  @"glyphicons-shower"			: @(ASDKGlyphIconTypeShower),
                                  @"glyphicons-menu-hamburger"	: @(ASDKGlyphIconTypeMenuHamburger),
                                  @"glyphicons-option-vertical"	: @(ASDKGlyphIconTypeOptionVertical),
                                  @"glyphicons-option-horizontal"   : @(ASDKGlyphIconTypeOptionHorizontal),
                                  @"glyphicons-currency-conversion" : @(ASDKGlyphIconTypeCurrencyConversion),
                                  @"glyphicons-user-ban"			: @(ASDKGlyphIconTypeUserBan),
                                  @"glyphicons-user-lock"		: @(ASDKGlyphIconTypeUserLock),
                                  @"glyphicons-user-flag"		: @(ASDKGlyphIconTypeUserFlag),
                                  @"glyphicons-user-asterisk"	: @(ASDKGlyphIconTypeUserAsterisk),
                                  @"glyphicons-user-alert"      : @(ASDKGlyphIconTypeUserAlert),
                                  @"glyphicons-user-key"		: @(ASDKGlyphIconTypeUserKey),
                                  @"glyphicons-user-conversation": @(ASDKGlyphIconTypeUserConversation),
                                  @"glyphicons-database"         : @(ASDKGlyphIconTypeDatabase),
                                  @"glyphicons-database-search"	: @(ASDKGlyphIconTypeDatabaseSearch),
                                  @"glyphicons-list-alt"		: @(ASDKGlyphIconTypeListAlt),
                                  @"glyphicons-hazard-sign"		: @(ASDKGlyphIconTypeHazardSign),
                                  @"glyphicons-hazard"          : @(ASDKGlyphIconTypeHazard),
                                  @"glyphicons-stop-sign"		: @(ASDKGlyphIconTypeStopSign),
                                  @"glyphicons-lab"				: @(ASDKGlyphIconTypeLab),
                                  @"glyphicons-lab-alt"			: @(ASDKGlyphIconTypeLabAlt),
                                  @"glyphicons-ice-cream"		: @(ASDKGlyphIconTypeIceCream),
                                  @"glyphicons-ice-lolly"		: @(ASDKGlyphIconTypeIceLolly),
                                  @"glyphicons-ice-lolly-tasted": @(ASDKGlyphIconTypeIceLollyTasted),
                                  @"glyphicons-invoice"			: @(ASDKGlyphIconTypeInvoice),
                                  @"glyphicons-cart-tick"		: @(ASDKGlyphIconTypeCartTick),
                                  @"glyphicons-hourglass"		: @(ASDKGlyphIconTypeHourglass),
                                  @"glyphicons-cat"				: @(ASDKGlyphIconTypeCat),
                                  @"glyphicons-lamp"			: @(ASDKGlyphIconTypeLamp),
                                  @"glyphicons-scale-classic"	: @(ASDKGlyphIconTypeScaleClassic),
                                  @"glyphicons-eye-plus"		: @(ASDKGlyphIconTypeEyePlus),
                                  @"glyphicons-eye-minus"		: @(ASDKGlyphIconTypeEyeMinus),
                                  @"glyphicons-quote"			: @(ASDKGlyphIconTypeQuote),
                                  @"glyphicons-bitcoin"			: @(ASDKGlyphIconTypeBitcoin),
                                  @"glyphicons-yen"				: @(ASDKGlyphIconTypeYen),
                                  @"glyphicons-ruble"			: @(ASDKGlyphIconTypeRuble),
                                  @"glyphicons-erase"			: @(ASDKGlyphIconTypeErase),
                                  @"glyphicons-podcast"			: @(ASDKGlyphIconTypePodcast),
                                  @"glyphicons-firework"		: @(ASDKGlyphIconTypeFirework),
                                  @"glyphicons-scale"			: @(ASDKGlyphIconTypeScale),
                                  @"glyphicons-king"			: @(ASDKGlyphIconTypeKing),
                                  @"glyphicons-queen"			: @(ASDKGlyphIconTypeQueen),
                                  @"glyphicons-pawn"			: @(ASDKGlyphIconTypePawn),
                                  @"glyphicons-bishop"			: @(ASDKGlyphIconTypeBishop),
                                  @"glyphicons-knight"			: @(ASDKGlyphIconTypeKnight),
                                  @"glyphicons-mic-mute"		: @(ASDKGlyphIconTypeMicMute),
                                  @"glyphicons-voicemail"		: @(ASDKGlyphIconTypeVoicemail),
                                  @"glyphicons-paragraph"		: @(ASDKGlyphIconTypeParagraph),
                                  @"glyphicons-person-walking"	: @(ASDKGlyphIconTypePersonWalking),
                                  @"glyphicons-person-wheelchair": @(ASDKGlyphIconTypePersonWheelchair),
                                  @"glyphicons-underground"		: @(ASDKGlyphIconTypeUnderground),
                                  @"glyphicons-car-hov"			: @(ASDKGlyphIconTypeCarHov),
                                  @"glyphicons-car-rental"      : @(ASDKGlyphIconTypeCarRental),
                                  @"glyphicons-transport"		: @(ASDKGlyphIconTypeTransport),
                                  @"glyphicons-taxi"			: @(ASDKGlyphIconTypeTaxi),
                                  @"glyphicons-ice-cream-no"	: @(ASDKGlyphIconTypeIceCreamNo),
                                  @"glyphicons-uk-rat-u"		: @(ASDKGlyphIconTypeUkRatU),
                                  @"glyphicons-uk-rat-pg"		: @(ASDKGlyphIconTypeUkRatPg),
                                  @"glyphicons-uk-rat-12a"		: @(ASDKGlyphIconTypeUkRat12a),
                                  @"glyphicons-uk-rat-12"		: @(ASDKGlyphIconTypeUkRat12),
                                  @"glyphicons-uk-rat-15"		: @(ASDKGlyphIconTypeUkRat15),
                                  @"glyphicons-uk-rat-18"		: @(ASDKGlyphIconTypeUkRat18),
                                  @"glyphicons-uk-rat-r18"		: @(ASDKGlyphIconTypeUkRatR18),
                                  @"glyphicons-tv"				: @(ASDKGlyphIconTypeTv),
                                  @"glyphicons-sms"				: @(ASDKGlyphIconTypeSms),
                                  @"glyphicons-mms"				: @(ASDKGlyphIconTypeMms),
                                  @"glyphicons-us-rat-g"		: @(ASDKGlyphIconTypeUsRatG),
                                  @"glyphicons-us-rat-pg"		: @(ASDKGlyphIconTypeUsRatPg),
                                  @"glyphicons-us-rat-pg-13"	: @(ASDKGlyphIconTypeUsRatPg13),
                                  @"glyphicons-us-rat-restricted": @(ASDKGlyphIconTypeUsRatRestricted),
                                  @"glyphicons-us-rat-no-one-17": @(ASDKGlyphIconTypeUsRatNoOne17),
                                  @"glyphicons-equalizer"		: @(ASDKGlyphIconTypeEqualizer),
                                  @"glyphicons-speakers"		: @(ASDKGlyphIconTypeSpeakers),
                                  @"glyphicons-remote-control"	: @(ASDKGlyphIconTypeRemoteControl),
                                  @"glyphicons-remote-control-tv": @(ASDKGlyphIconTypeRemoteControlTv),
                                  @"glyphicons-shredder"		: @(ASDKGlyphIconTypeShredder),
                                  @"glyphicons-folder-heart"	: @(ASDKGlyphIconTypeFolderHeart),
                                  @"glyphicons-person-running"	: @(ASDKGlyphIconTypePersonRunning),
                                  @"glyphicons-person"			: @(ASDKGlyphIconTypePerson),
                                  @"glyphicons-voice"			: @(ASDKGlyphIconTypeVoice),
                                  @"glyphicons-stethoscope"		: @(ASDKGlyphIconTypeStethoscope),
                                  @"glyphicons-hotspot"         : @(ASDKGlyphIconTypeHotspot),
                                  @"glyphicons-activity"		: @(ASDKGlyphIconTypeActivity),
                                  @"glyphicons-watch"			: @(ASDKGlyphIconTypeWatch),
                                  @"glyphicons-scissors-alt"	: @(ASDKGlyphIconTypeScissorsAlt),
                                  @"glyphicons-car-wheel"		: @(ASDKGlyphIconTypeCarWheel),
                                  @"glyphicons-chevron-up"		: @(ASDKGlyphIconTypeChevronUp),
                                  @"glyphicons-chevron-down"	: @(ASDKGlyphIconTypeChevronDown),
                                  @"glyphicons-superscript"		: @(ASDKGlyphIconTypeSuperscript),
                                  @"glyphicons-subscript"		: @(ASDKGlyphIconTypeSubscript),
                                  @"glyphicons-text-size"		: @(ASDKGlyphIconTypeTextSize),
                                  @"glyphicons-text-color"		: @(ASDKGlyphIconTypeTextColor),
                                  @"glyphicons-text-background"	: @(ASDKGlyphIconTypeTextBackground),
                                  @"glyphicons-modal-window"	: @(ASDKGlyphIconTypeModalWindow),
                                  @"glyphicons-newspaper"		: @(ASDKGlyphIconTypeNewspaper),
                                  @"glyphicons-tractor"         : @(ASDKGlyphIconTypeTractor)
                                };
    });
    
    return iconsDescriptionsDict;
}

@end
